"""FLASH-seq UMI analysis pipeline generator (fastq to result), protocol section 12.

Method: FLASH-seq UMI v3, Picelli & Hahaut, protocols.io 2022,
DOI 10.17504/protocols.io.bp2l619rdvqe/v3 (CC-BY). The shell commands below are
transcribed faithfully from section 12 (they are not simplified): full umi_tools
regex for UMI-in-R1 and UMI-in-R2, double-UMI filtering, internal vs UMI read
separation, orientation reconciliation, separate mapping of UMI and internal reads,
and the exact featureCounts + umi_tools count commands.

Exposed over MCP so an agent can generate the downstream analysis alongside the
wet-lab tools. The generated scripts call EXTERNAL tools that are not bundled here
(bcl2fastq, umi_tools, STAR, samtools, featureCounts, bbmap, scanpy); the shell
pipeline preflights for them. RESEARCH USE ONLY.
"""

from __future__ import annotations

import os

# Faithful transcription of protocol section 12 (12.1 to 12.12). Shell variables let
# the user set paths/ids at runtime, exactly as the protocol does. @@TOKENS@@ are
# filled by generate_pipeline_sh.
_PIPELINE_TEMPLATE = r'''#!/usr/bin/env bash
# flashseq_pipeline.sh -- FLASH-seq UMI analysis, fastq to counts (protocol section 12).
# Method: FLASH-seq UMI v3, Picelli & Hahaut, protocols.io 2022,
# DOI 10.17504/protocols.io.bp2l619rdvqe/v3 (CC-BY). Generated by plr-mcp. Author: di.
# RESEARCH USE ONLY. External tools (install separately): bcl2fastq, umi_tools, STAR,
# samtools, featureCounts, bbmap.
set -euo pipefail

# ---- 0. Variables (edit these) ----
BASECALL_DIR="${BASECALL_DIR:-/path/to/flowcell/Data/Intensities/BaseCalls/}"
OUTPUT_DIR="${OUTPUT_DIR:-./out}"
SAMPLESHEET="${SAMPLESHEET:-/path/to/Demultiplexing_SampleSheet.csv}"
GENOME="${GENOME:-/path/to/STAR_indexed_genome/}"
FASTA="${FASTA:-GRCh38.primary_assembly.genome.fa}"
GTF="${GTF:-gencode.v34.primary_assembly.annotation.gtf}"
READ_LENGTH="${READ_LENGTH:-@@READ_LENGTH@@}"
SJDB_OVERHANG=$(( READ_LENGTH - 1 ))
ID="${ID:-sample_id}"
THREADS="${THREADS:-10}"
BBMAP_filter="${BBMAP_filter:-filterbyname.sh}"
STRAND="${STRAND:-@@STRAND@@}"

for tool in bcl2fastq umi_tools STAR samtools featureCounts; do
  command -v "$tool" >/dev/null 2>&1 || echo "[plr-mcp] MISSING external tool: $tool" >&2
done

# ---- 12.1 bcl2fastq ----
ulimit -n 10000 || true
bcl2fastq --input-dir "$BASECALL_DIR" --output-dir "$OUTPUT_DIR" \
  --sample-sheet "$SAMPLESHEET" --create-fastq-for-index-reads --no-lane-splitting

# ---- 12.2 Genome index (run ONCE per genome/read length; uncomment) ----
# STAR --runThreadN 15 --runMode genomeGenerate --genomeDir "$GENOME" \
#   --genomeFastaFiles "$FASTA" --sjdbGTFfile "$GTF" --sjdbOverhang "$SJDB_OVERHANG"

# ---- 12.3 UMI extraction: UMI in R1 and UMI in R2 (spacer CTAAC, 8 bp UMI, regex) ----
umi_tools extract --extract-method=regex \
  --bc-pattern="^(?P<discard_1>AAGCAGTGGTATCAACGCAGAGT|AGCAGTGGTATCAACGCAGAGT|GCAGTGGTATCAACGCAGAGT|CAGTGGTATCAACGCAGAGT|AGTGGTATCAACGCAGAGT|GTGGTATCAACGCAGAGT|TGGTATCAACGCAGAGT|GGTATCAACGCAGAGT|GTATCAACGCAGAGT|ATCAACGCAGAGT|CAACGCAGAGT|AACGCAGAGT|ACGCAGAGT|GCAGAGT|CAGAGT|AGAGT|GAGT|AGT|GT)(?P<umi_1>.{8})(?P<discard_2>CTAACGG)(?P<discard_3>G{0,4})" \
  --stdin="$ID".R1.fastq.gz --stdout=umi.UMIinR1.R1.fq \
  --read2-in="$ID".R2.fastq.gz --read2-out=umi.UMIinR1.R2.fq

umi_tools extract --extract-method=regex \
  --bc-pattern="^(?P<discard_1>GAGT|AGT|GT)(?P<umi_1>.{8})(?P<discard_2>CTAACGG)(?P<discard_3>G{0,4})" \
  --stdin="$ID".R2.fastq.gz --stdout=umi.UMIinR2.R2.fq \
  --read2-in="$ID".R1.fastq.gz --read2-out=umi.UMIinR2.R1.fq

# rare: a UMI in BOTH R1 and R2; find and filter those out of the UMI reads
cat umi.UMIinR1.R1.fq | uniq | awk 'NR%4==1{print}' | sed 's/@//g' > names.R1umi.txt
cat umi.UMIinR2.R1.fq | uniq | awk 'NR%4==1{print}' | sed 's/@//g' > names.R2umi.txt
cat names.R1umi.txt | sed 's/_........ .*$//g' > names.R1umi.cleaned
cat names.R2umi.txt | sed 's/_........ .*$//g' > names.R2umi.cleaned
comm -12 <(sort names.R1umi.cleaned) <(sort names.R2umi.cleaned) > R1R2.toFilterOut
grep -f R1R2.toFilterOut names.R1umi.txt > R1.toFilterOut || true
grep -f R1R2.toFilterOut names.R2umi.txt > R2.toFilterOut || true
"$BBMAP_filter" in=umi.UMIinR1.R1.fq in2=umi.UMIinR1.R2.fq out=umi.UMIinR1.R1.tmp out2=umi.UMIinR1.R2.tmp names=R1.toFilterOut include=f overwrite=t
"$BBMAP_filter" in=umi.UMIinR2.R1.fq in2=umi.UMIinR2.R2.fq out=umi.UMIinR2.R1.tmp out2=umi.UMIinR2.R2.tmp names=R2.toFilterOut include=f overwrite=t
mv umi.UMIinR1.R1.tmp umi.UMIinR1.R1.fq; mv umi.UMIinR2.R1.tmp umi.UMIinR2.R1.fq
mv umi.UMIinR1.R2.tmp umi.UMIinR1.R2.fq; mv umi.UMIinR2.R2.tmp umi.UMIinR2.R2.fq

# ---- 12.4 Separate internal reads (exclude the UMI read ids) ----
cat umi.UMIinR1.R1.fq | uniq | awk 'NR%4==1{print}' | sed 's/@//g' | sed 's/_........//g' > names.R1umi.txt
cat umi.UMIinR2.R1.fq | uniq | awk 'NR%4==1{print}' | sed 's/@//g' | sed 's/_........//g' > names.R2umi.txt
sed -i 's/_........//g' R1.toFilterOut || true
sed -i 's/_........//g' R2.toFilterOut || true
cat names.R1umi.txt names.R2umi.txt R1.toFilterOut R2.toFilterOut > names.umi.txt
"$BBMAP_filter" in="$ID".R1.fastq.gz in2="$ID".R2.fastq.gz out=internal.R1.fq out2=internal.R2.fq names=names.umi.txt include=f overwrite=t

# ---- 12.5 Reconcile UMI read orientations ----
cat umi.UMIinR1.R1.fq umi.UMIinR2.R2.fq > umi.R1.fq
cat umi.UMIinR1.R2.fq umi.UMIinR2.R1.fq > umi.R2.fq

# ---- 12.6 Optional adapter/primer trimming with bbduk (uncomment if leftovers seen) ----
# bbduk.sh in1=umi.R1.fq in2=umi.R2.fq out1=umi.R1.trim.fq out2=umi.R2.trim.fq \
#   ktrim=r ref=adapters.fa k=23 mink=7 hdist=1 minlength=29 tbo

# ---- 12.7 Map UMI reads; keep primary mapped (-F 260) ----
mkdir -p STAR
STAR --runThreadN "$THREADS" --limitBAMsortRAM 20000000000 --genomeLoad LoadAndKeep \
  --genomeDir "$GENOME" --readFilesIn umi.R1.fq umi.R2.fq --readFilesCommand cat \
  --limitSjdbInsertNsj 2000000 --seedSearchStartLmax 30 \
  --outFilterIntronMotifs RemoveNoncanonicalUnannotated \
  --outSAMtype BAM SortedByCoordinate --outFileNamePrefix STAR/"$ID"_UMI_
samtools view -@ 5 -Sb -F 260 STAR/"$ID"_UMI_Aligned.sortedByCoord.out.bam > "$ID"_UMI.filtered.bam
samtools index "$ID"_UMI.filtered.bam

# ---- 12.8 Map internal reads ----
STAR --runThreadN "$THREADS" --limitBAMsortRAM 20000000000 --genomeLoad LoadAndKeep \
  --genomeDir "$GENOME" --readFilesIn internal.R1.fq internal.R2.fq --readFilesCommand cat \
  --limitSjdbInsertNsj 2000000 --outFilterIntronMotifs RemoveNoncanonicalUnannotated \
  --outSAMtype BAM SortedByCoordinate --outFileNamePrefix STAR/"$ID"_INTERNAL_
samtools view -@ 5 -Sb -F 260 STAR/"$ID"_INTERNAL_Aligned.sortedByCoord.out.bam > "$ID"_INTERNAL.filtered.bam
samtools index "$ID"_INTERNAL.filtered.bam

# ---- 12.10 Count matrix, UMI reads (assign to features, then dedup) ----
mkdir -p FEATURECOUNTS
featureCounts -T 1 -p -t exon -g gene_name -s "$STRAND" --fracOverlap 0.25 -a "$GTF" -R BAM \
  -o FEATURECOUNTS/"$ID"_Aligned.txt "$ID"_UMI.filtered.bam
samtools sort -@ "$THREADS" "$ID"_UMI.filtered.bam.featureCounts.bam -o FEATURECOUNTS/"$ID"_UMI.fc.sorted.bam
samtools index FEATURECOUNTS/"$ID"_UMI.fc.sorted.bam
umi_tools count --per-gene --paired --gene-tag=XT --chimeric-pairs=discard --unpaired-reads=discard \
  --assigned-status-tag=XS -I FEATURECOUNTS/"$ID"_UMI.fc.sorted.bam -S FEATURECOUNTS/"$ID".umi.counts.tsv.gz

# ---- 12.11 Count matrix, internal reads (no UMI dedup) ----
featureCounts -T 1 -p -t exon -g gene_name --fracOverlap 0.25 -a "$GTF" \
  -o FEATURECOUNTS/"$ID"_INTERNAL_featureCounts.txt "$ID"_INTERNAL.filtered.bam

# ---- 12.12 Post-processing handoff (Seurat or scanpy) ----
if command -v python3 >/dev/null 2>&1 && python3 -c "import scanpy" 2>/dev/null; then
  python3 flashseq_analysis.py
else
  echo "[plr-mcp] UMI counts in FEATURECOUNTS/*.umi.counts.tsv.gz. Next: Seurat, or python3 flashseq_analysis.py."
fi
'''


def generate_pipeline_sh(*, read_length: int = 100, strand: int = 1) -> str:
    """Return the faithful FLASH-seq UMI fastq-to-counts pipeline (protocol section 12).

    `read_length` sets the STAR sjdbOverhang default (read_length - 1). `strand` sets
    featureCounts -s for the UMI reads (the protocol uses 1). Other values are the
    protocol's exact values, transcribed verbatim.
    """
    return _PIPELINE_TEMPLATE.replace("@@READ_LENGTH@@", str(read_length)).replace(
        "@@STRAND@@", str(strand)
    )


def generate_scanpy_analysis(
    *,
    min_genes_per_cell: int = 200,
    min_cells_per_gene: int = 3,
    max_pct_mito: float = 20,
    n_top_hvg: int = 2000,
    n_pcs: int = 30,
    leiden_resolution: float = 1.0,
) -> str:
    """Return a scanpy post-processing script (protocol section 12.12 handoff).

    Section 12.12 leaves post-processing to Seurat or scanpy and gives no parameters,
    so the values here are sensible defaults, not protocol values.
    """
    return f'''#!/usr/bin/env python3
"""flashseq_analysis.py -- FLASH-seq UMI post-processing (protocol section 12.12).
Assembles the umi_tools count matrices and runs a standard scanpy workflow. Generated
by plr-mcp. RESEARCH USE ONLY. Author: di. EXTERNAL DEPENDENCY: scanpy."""
import glob
import os
import sys

try:
    import anndata as ad
    import pandas as pd
    import scanpy as sc
except ImportError:
    sys.exit("[plr-mcp] Missing dependency: scanpy/pandas/anndata. pip install scanpy")

COUNTS_GLOB = os.environ.get("COUNTS_GLOB", "FEATURECOUNTS/*.umi.counts.tsv.gz")
OUT_H5AD = os.environ.get("OUT_H5AD", "flashseq.analyzed.h5ad")
MIN_GENES_PER_CELL = {min_genes_per_cell}
MIN_CELLS_PER_GENE = {min_cells_per_gene}
MAX_PCT_MITO = {max_pct_mito}
N_TOP_HVG = {n_top_hvg}
N_PCS = {n_pcs}
LEIDEN_RESOLUTION = {leiden_resolution}


def load_counts(pattern):
    files = sorted(glob.glob(pattern))
    if not files:
        sys.exit(f"[plr-mcp] No count matrices matched {{pattern}}. Run flashseq_pipeline.sh first.")
    series = {{}}
    for f in files:
        cell = os.path.basename(f).split(".umi.counts")[0]
        df = pd.read_csv(f, sep="\\t")
        gene_col = "gene" if "gene" in df.columns else df.columns[0]
        count_col = "count" if "count" in df.columns else df.columns[-1]
        series[cell] = df.set_index(gene_col)[count_col]
    return ad.AnnData(pd.DataFrame(series).fillna(0).T)


def main():
    adata = load_counts(COUNTS_GLOB)
    print(f"[plr-mcp] Loaded {{adata.n_obs}} cells x {{adata.n_vars}} genes")
    sc.pp.filter_cells(adata, min_genes=MIN_GENES_PER_CELL)
    sc.pp.filter_genes(adata, min_cells=MIN_CELLS_PER_GENE)
    adata.var["mito"] = adata.var_names.str.upper().str.startswith(("MT-", "MT."))
    sc.pp.calculate_qc_metrics(adata, qc_vars=["mito"], inplace=True, percent_top=None)
    adata = adata[adata.obs["pct_counts_mito"] < MAX_PCT_MITO].copy()
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata)
    sc.pp.highly_variable_genes(adata, n_top_genes=N_TOP_HVG)
    adata.raw = adata
    adata = adata[:, adata.var["highly_variable"]].copy()
    sc.pp.scale(adata, max_value=10)
    sc.tl.pca(adata, n_comps=min(N_PCS, adata.n_obs - 1, adata.n_vars - 1))
    sc.pp.neighbors(adata, n_pcs=min(N_PCS, adata.n_obs - 1))
    sc.tl.leiden(adata, resolution=LEIDEN_RESOLUTION)
    sc.tl.umap(adata)
    sc.tl.rank_genes_groups(adata, "leiden", method="wilcoxon")
    adata.write(OUT_H5AD)
    print(f"[plr-mcp] Wrote {{OUT_H5AD}} with {{adata.obs['leiden'].nunique()}} clusters.")


if __name__ == "__main__":
    main()
'''


def generate_analysis(out_dir: str = "analysis_out", **params) -> dict:
    """Write the faithful FLASH-seq UMI pipeline (shell + scanpy) into out_dir.

    Returns the paths written, the external tools required, and the ordered steps.
    """
    os.makedirs(out_dir, exist_ok=True)
    sh_keys = {"read_length", "strand"}
    py_keys = {
        "min_genes_per_cell",
        "min_cells_per_gene",
        "max_pct_mito",
        "n_top_hvg",
        "n_pcs",
        "leiden_resolution",
    }
    sh_params = {k: v for k, v in params.items() if k in sh_keys}
    py_params = {k: v for k, v in params.items() if k in py_keys}

    sh_path = os.path.join(out_dir, "flashseq_pipeline.sh")
    py_path = os.path.join(out_dir, "flashseq_analysis.py")
    with open(sh_path, "w", encoding="utf-8") as fh:
        fh.write(generate_pipeline_sh(**sh_params))
    os.chmod(sh_path, 0o755)
    with open(py_path, "w", encoding="utf-8") as fh:
        fh.write(generate_scanpy_analysis(**py_params))
    os.chmod(py_path, 0o755)

    return {
        "pipeline_sh": sh_path,
        "analysis_py": py_path,
        "method": "FLASH-seq UMI v3, DOI 10.17504/protocols.io.bp2l619rdvqe/v3 (CC-BY), section 12",
        "steps": [
            "12.1 bcl2fastq",
            "12.3 umi_tools extract UMI-in-R1 and UMI-in-R2 (full regex, CTAAC spacer, 8 bp), filter double-UMI reads",
            "12.4 separate internal reads",
            "12.5 reconcile UMI read orientations",
            "12.7 STAR map UMI reads, samtools -F 260",
            "12.8 STAR map internal reads",
            "12.10 featureCounts (-s 1) then umi_tools count (dedup) for UMI reads",
            "12.11 featureCounts for internal reads",
            "12.12 scanpy or Seurat post-processing",
        ],
        "external_tools": [
            "bcl2fastq",
            "umi_tools",
            "STAR",
            "samtools",
            "featureCounts",
            "bbmap",
            "scanpy",
        ],
        "note": "Commands transcribed faithfully from protocol section 12. External tools not bundled. RESEARCH USE ONLY.",
    }
