"""Tool-agnostic single-cell RNA-seq workflow generator.

The generated workflow defines stable file and command contracts while leaving
demultiplexing, UMI preprocessing, alignment, counting, and downstream analysis
to user-selected executables. UMI patterns remain runtime configuration, so the
workflow is independent of both library-preparation kits and analysis stacks.

Exposed over MCP so an agent can generate the downstream workflow alongside the
wet-lab tools. External hook implementations are not bundled. RESEARCH USE ONLY.
"""

from __future__ import annotations

import os


_PIPELINE_TEMPLATE = r"""#!/usr/bin/env bash
# scrnaseq_pipeline.sh -- tool-agnostic single-cell RNA-seq workflow.
# Generated by plr-mcp. Author: di.
# RESEARCH USE ONLY. Configure executable hooks before running.
set -euo pipefail

# ---- Inputs and neutral workflow metadata ----
RAW_INPUT_DIR="${RAW_INPUT_DIR:-}"
FASTQ_DIR="${FASTQ_DIR:-./fastq}"
SAMPLE_ID="${SAMPLE_ID:-sample_id}"
INPUT_R1="${INPUT_R1:-$FASTQ_DIR/$SAMPLE_ID.R1.fastq.gz}"
INPUT_R2="${INPUT_R2:-$FASTQ_DIR/$SAMPLE_ID.R2.fastq.gz}"
REFERENCE="${REFERENCE:-/path/to/reference}"
ANNOTATION="${ANNOTATION:-/path/to/annotation}"
WORK_DIR="${WORK_DIR:-./work}"
COUNT_MATRIX="${COUNT_MATRIX:-./counts/$SAMPLE_ID.umi_counts.tsv}"
ANALYSIS_OUTPUT="${ANALYSIS_OUTPUT:-./analysis/$SAMPLE_ID}"
THREADS="${THREADS:-10}"
READ_LENGTH="${READ_LENGTH:-@@READ_LENGTH@@}"
STRANDEDNESS="${STRANDEDNESS:-@@STRAND@@}"
UMI_PATTERN_R1="${UMI_PATTERN_R1:-^(?P<umi_1>.{8})}"
UMI_PATTERN_R2="${UMI_PATTERN_R2:-^(?P<umi_1>.{8})}"

# ---- User-selected executable hooks ----
# Each value must name one executable (use a wrapper script when extra setup is
# needed). The optional demultiplexing hook writes INPUT_R1 and INPUT_R2.
DEMULTIPLEX_HOOK="${DEMULTIPLEX_HOOK:-}"
UMI_PREPROCESS_HOOK="${UMI_PREPROCESS_HOOK:-}"
ALIGNMENT_HOOK="${ALIGNMENT_HOOK:-}"
COUNTING_HOOK="${COUNTING_HOOK:-}"
SCRNASEQ_POSTPROCESS_HOOK="${SCRNASEQ_POSTPROCESS_HOOK:-}"

UMI_R1="$WORK_DIR/umi.R1.fastq.gz"
UMI_R2="$WORK_DIR/umi.R2.fastq.gz"
INTERNAL_R1="$WORK_DIR/internal.R1.fastq.gz"
INTERNAL_R2="$WORK_DIR/internal.R2.fastq.gz"
UMI_ALIGNMENT="$WORK_DIR/umi.alignment"
INTERNAL_ALIGNMENT="$WORK_DIR/internal.alignment"

invoke_hook() {
  local variable_name="$1"
  shift
  local hook="${!variable_name:-}"
  if [[ -z "$hook" ]]; then
    echo "[plr-mcp] Missing required hook: $variable_name" >&2
    exit 2
  fi
  if [[ ! -x "$hook" ]] && ! command -v "$hook" >/dev/null 2>&1; then
    echo "[plr-mcp] Hook is not executable or on PATH: $variable_name=$hook" >&2
    exit 2
  fi
  "$hook" "$@"
}

require_output() {
  local output_path="$1"
  if [[ ! -e "$output_path" ]]; then
    echo "[plr-mcp] Expected workflow output was not created: $output_path" >&2
    exit 3
  fi
}

mkdir -p "$FASTQ_DIR" "$WORK_DIR" "$(dirname "$COUNT_MATRIX")" "$ANALYSIS_OUTPUT"

# ---- Optional raw-data demultiplexing ----
if [[ -n "$DEMULTIPLEX_HOOK" ]]; then
  invoke_hook DEMULTIPLEX_HOOK \
    --input "$RAW_INPUT_DIR" \
    --sample-id "$SAMPLE_ID" \
    --output-r1 "$INPUT_R1" \
    --output-r2 "$INPUT_R2"
fi
require_output "$INPUT_R1"
require_output "$INPUT_R2"

# ---- UMI-aware preprocessing ----
# Contract: extract UMIs using the supplied patterns, exclude reads carrying
# conflicting UMIs in both mates, preserve UMI identity, and split UMI-bearing
# from internal reads into the four requested outputs.
invoke_hook UMI_PREPROCESS_HOOK \
  --r1 "$INPUT_R1" \
  --r2 "$INPUT_R2" \
  --umi-pattern-r1 "$UMI_PATTERN_R1" \
  --umi-pattern-r2 "$UMI_PATTERN_R2" \
  --umi-r1 "$UMI_R1" \
  --umi-r2 "$UMI_R2" \
  --internal-r1 "$INTERNAL_R1" \
  --internal-r2 "$INTERNAL_R2"
for output_path in "$UMI_R1" "$UMI_R2" "$INTERNAL_R1" "$INTERNAL_R2"; do
  require_output "$output_path"
done

# ---- Alignment ----
# The same hook handles both read classes and may emit any alignment format, as
# long as the counting hook understands it.
invoke_hook ALIGNMENT_HOOK \
  --read-class umi \
  --r1 "$UMI_R1" \
  --r2 "$UMI_R2" \
  --reference "$REFERENCE" \
  --annotation "$ANNOTATION" \
  --read-length "$READ_LENGTH" \
  --threads "$THREADS" \
  --output "$UMI_ALIGNMENT"
invoke_hook ALIGNMENT_HOOK \
  --read-class internal \
  --r1 "$INTERNAL_R1" \
  --r2 "$INTERNAL_R2" \
  --reference "$REFERENCE" \
  --annotation "$ANNOTATION" \
  --read-length "$READ_LENGTH" \
  --threads "$THREADS" \
  --output "$INTERNAL_ALIGNMENT"
require_output "$UMI_ALIGNMENT"
require_output "$INTERNAL_ALIGNMENT"

# ---- UMI-aware gene counting ----
# Contract: use UMI identity to deduplicate UMI-bearing reads, incorporate the
# internal-read alignment according to the selected method, and write a
# gene-by-cell count matrix to COUNT_MATRIX.
invoke_hook COUNTING_HOOK \
  --umi-alignment "$UMI_ALIGNMENT" \
  --internal-alignment "$INTERNAL_ALIGNMENT" \
  --annotation "$ANNOTATION" \
  --strandedness "$STRANDEDNESS" \
  --threads "$THREADS" \
  --output "$COUNT_MATRIX"
require_output "$COUNT_MATRIX"

# ---- Optional downstream analysis ----
if [[ -n "$SCRNASEQ_POSTPROCESS_HOOK" ]]; then
  export COUNT_MATRIX ANALYSIS_OUTPUT SCRNASEQ_POSTPROCESS_HOOK
  python3 scrnaseq_analysis.py
else
  echo "[plr-mcp] Count matrix ready: $COUNT_MATRIX"
  echo "[plr-mcp] Set SCRNASEQ_POSTPROCESS_HOOK to run downstream QC and clustering."
fi
"""


def generate_pipeline_sh(*, read_length: int = 100, strand: int = 1) -> str:
    """Return a hook-driven single-cell RNA-seq FASTQ-to-counts workflow.

    ``read_length`` and ``strand`` are neutral metadata passed to the selected
    alignment and counting hooks. Library-specific UMI patterns remain runtime
    configuration through ``UMI_PATTERN_R1`` and ``UMI_PATTERN_R2``.
    """
    return _PIPELINE_TEMPLATE.replace("@@READ_LENGTH@@", str(read_length)).replace(
        "@@STRAND@@", str(strand)
    )


_POSTPROCESS_TEMPLATE = r'''#!/usr/bin/env python3
"""scrnaseq_analysis.py -- dispatch downstream analysis to a configured hook.

The hook receives a count matrix plus neutral QC, feature-selection,
dimensionality, and clustering parameters. It chooses the implementation and
output format. Generated by plr-mcp. RESEARCH USE ONLY.
"""
from __future__ import annotations

import os
from pathlib import Path
import shutil
import subprocess
import sys


COUNT_MATRIX = os.environ.get("COUNT_MATRIX", "./counts/sample_id.umi_counts.tsv")
ANALYSIS_OUTPUT = os.environ.get("ANALYSIS_OUTPUT", "./analysis/sample_id")
POSTPROCESS_HOOK = os.environ.get("SCRNASEQ_POSTPROCESS_HOOK", "")
MIN_GENES_PER_CELL = @@MIN_GENES_PER_CELL@@
MIN_CELLS_PER_GENE = @@MIN_CELLS_PER_GENE@@
MAX_PCT_MITO = @@MAX_PCT_MITO@@
N_TOP_FEATURES = @@N_TOP_FEATURES@@
N_COMPONENTS = @@N_COMPONENTS@@
CLUSTER_RESOLUTION = @@CLUSTER_RESOLUTION@@


def main() -> int:
    if not POSTPROCESS_HOOK:
        sys.exit("[plr-mcp] Set SCRNASEQ_POSTPROCESS_HOOK to an executable analysis adapter.")
    if not Path(COUNT_MATRIX).exists():
        sys.exit(f"[plr-mcp] Count matrix not found: {COUNT_MATRIX}")
    if not Path(POSTPROCESS_HOOK).is_file() and shutil.which(POSTPROCESS_HOOK) is None:
        sys.exit(f"[plr-mcp] Analysis hook is not executable or on PATH: {POSTPROCESS_HOOK}")

    Path(ANALYSIS_OUTPUT).mkdir(parents=True, exist_ok=True)
    command = [
        POSTPROCESS_HOOK,
        "--counts", COUNT_MATRIX,
        "--output", ANALYSIS_OUTPUT,
        "--min-genes-per-cell", str(MIN_GENES_PER_CELL),
        "--min-cells-per-gene", str(MIN_CELLS_PER_GENE),
        "--max-pct-mito", str(MAX_PCT_MITO),
        "--top-features", str(N_TOP_FEATURES),
        "--components", str(N_COMPONENTS),
        "--cluster-resolution", str(CLUSTER_RESOLUTION),
    ]
    subprocess.run(command, check=True)
    print(f"[plr-mcp] Downstream analysis complete: {ANALYSIS_OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def generate_postprocess_driver(
    *,
    min_genes_per_cell: int = 200,
    min_cells_per_gene: int = 3,
    max_pct_mito: float = 20,
    n_top_features: int = 2000,
    n_components: int = 30,
    cluster_resolution: float = 1.0,
) -> str:
    """Return a neutral downstream-analysis hook dispatcher."""
    replacements = {
        "@@MIN_GENES_PER_CELL@@": str(min_genes_per_cell),
        "@@MIN_CELLS_PER_GENE@@": str(min_cells_per_gene),
        "@@MAX_PCT_MITO@@": str(max_pct_mito),
        "@@N_TOP_FEATURES@@": str(n_top_features),
        "@@N_COMPONENTS@@": str(n_components),
        "@@CLUSTER_RESOLUTION@@": str(cluster_resolution),
    }
    rendered = _POSTPROCESS_TEMPLATE
    for token, value in replacements.items():
        rendered = rendered.replace(token, value)
    return rendered


def generate_analysis(out_dir: str = "analysis_out", **params) -> dict:
    """Write a tool-agnostic UMI-aware single-cell RNA-seq workflow."""
    os.makedirs(out_dir, exist_ok=True)
    sh_keys = {"read_length", "strand"}
    py_keys = {
        "min_genes_per_cell",
        "min_cells_per_gene",
        "max_pct_mito",
        "n_top_features",
        "n_components",
        "cluster_resolution",
    }
    sh_params = {key: value for key, value in params.items() if key in sh_keys}
    py_params = {key: value for key, value in params.items() if key in py_keys}

    sh_path = os.path.join(out_dir, "scrnaseq_pipeline.sh")
    py_path = os.path.join(out_dir, "scrnaseq_analysis.py")
    with open(sh_path, "w", encoding="utf-8") as handle:
        handle.write(generate_pipeline_sh(**sh_params))
    os.chmod(sh_path, 0o755)
    with open(py_path, "w", encoding="utf-8") as handle:
        handle.write(generate_postprocess_driver(**py_params))
    os.chmod(py_path, 0o755)

    return {
        "pipeline_sh": sh_path,
        "analysis_py": py_path,
        "method": "single-cell RNA-seq with configurable UMI extraction",
        "steps": [
            "optional demultiplexing through a configured hook",
            "configurable UMI extraction, double-UMI filtering, and internal-read separation",
            "alignment of UMI-bearing and internal reads through a configured hook",
            "UMI-aware gene-by-cell counting through a configured hook",
            "optional QC, dimensionality reduction, clustering, and marker analysis through a configured hook",
        ],
        "required_hooks": [
            "UMI_PREPROCESS_HOOK",
            "ALIGNMENT_HOOK",
            "COUNTING_HOOK",
        ],
        "optional_hooks": [
            "DEMULTIPLEX_HOOK",
            "SCRNASEQ_POSTPROCESS_HOOK",
        ],
        "external_tools": [],
        "note": (
            "Library-specific UMI patterns and all analysis implementations are runtime "
            "configuration. Hook implementations are not bundled. RESEARCH USE ONLY."
        ),
    }
